export const mockCredentials = {
  admin: {
    email: 'admin@srms.edu',
    password: 'admin123',
    name: 'Dr. Sarah Jenkins',
    role: 'Administrator',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150'
  },
  staff: [
    {
      email: 'advisor@srms.edu',
      password: 'advisor123',
      name: 'Prof. Rajesh Kumar',
      department: 'IT',
      role: 'Faculty Advisor',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150'
    },
    {
      email: 'aids_advisor@srms.edu',
      password: 'advisor123',
      name: 'Dr. Anita Desai',
      department: 'AIDS',
      role: 'Senior Advisor',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150'
    }
  ]
};

export const initialStudents = [
  {
    id: 1,
    name: 'Aravind Swamy',
    rollNumber: '22IT001',
    department: 'IT',
    year: '3rd Year',
    email: 'aravind.22it001@srms.edu',
    phone: '+91 94421 87601',
    gpa: 8.92,
    attendance: 94,
    status: 'Active',
    performanceSummary: 'Exceptional in Software Engineering and Database Management Systems. Currently leading the department coding club.',
    courses: ['Database Systems', 'Software Engineering', 'Computer Networks', 'Java Programming']
  },
  {
    id: 2,
    name: 'Bhavana Reddy',
    rollNumber: '23AD001',
    department: 'AIDS',
    year: '2nd Year',
    email: 'bhavana.23ad001@srms.edu',
    phone: '+91 98402 12345',
    gpa: 9.45,
    attendance: 98,
    status: 'Active',
    performanceSummary: 'Brilliant student with high interest in Machine Learning. Won first prize in the national level AI hackathon.',
    courses: ['Machine Learning Basics', 'Probability & Statistics', 'Python Programming', 'Data Structures']
  },
  {
    id: 3,
    name: 'Chaitanya Kiran',
    rollNumber: '21IT045',
    department: 'IT',
    year: '4th Year',
    email: 'chaitanya.21it045@srms.edu',
    phone: '+91 81223 98765',
    gpa: 7.85,
    attendance: 82,
    status: 'Active',
    performanceSummary: 'Strong coding capabilities in Web Technologies. Has completed an internship as a Front-end Developer at a startup.',
    courses: ['Cloud Computing', 'Information Security', 'Web Technology', 'Professional Elective']
  },
  {
    id: 4,
    name: 'Divya Bharathi',
    rollNumber: '24AD012',
    department: 'AIDS',
    year: '1st Year',
    email: 'divya.24ad012@srms.edu',
    phone: '+91 97910 11223',
    gpa: 8.12,
    attendance: 90,
    status: 'Active',
    performanceSummary: 'Quick learner with active participation in classroom discussions. Showing great promise in linear algebra.',
    courses: ['Linear Algebra', 'Problem Solving Techniques', 'Physics for Computing', 'English Communication']
  },
  {
    id: 5,
    name: 'Eshwar Prasad',
    rollNumber: '22IT018',
    department: 'IT',
    year: '3rd Year',
    email: 'eshwar.22it018@srms.edu',
    phone: '+91 73581 44556',
    gpa: 6.95,
    attendance: 78,
    status: 'Active',
    performanceSummary: 'Good hands-on skills in networking. Working on improving theoretical understanding and lab performance.',
    courses: ['Computer Networks', 'Operating Systems', 'Design & Analysis of Algorithms', 'Environmental Science']
  },
  {
    id: 6,
    name: 'Farhan Akhtar',
    rollNumber: '23AD022',
    department: 'AIDS',
    year: '2nd Year',
    email: 'farhan.23ad022@srms.edu',
    phone: '+91 95000 66778',
    gpa: 8.56,
    attendance: 88,
    status: 'Active',
    performanceSummary: 'Exhibits analytical thinking in Data Science challenges. Actively involved in sports and community service.',
    courses: ['Foundations of Data Science', 'Python Programming', 'Discrete Mathematics', 'Digital Logic']
  },
  {
    id: 7,
    name: 'Goutham Menon',
    rollNumber: '21AD003',
    department: 'AIDS',
    year: '4th Year',
    email: 'goutham.21ad003@srms.edu',
    phone: '+91 80562 33445',
    gpa: 9.15,
    attendance: 92,
    status: 'Active',
    performanceSummary: 'Consistently outstanding academic performance. Working on a capstone project targeting automated medical imaging analysis.',
    courses: ['Deep Learning', 'Natural Language Processing', 'Big Data Analytics', 'Project Work II']
  },
  {
    id: 8,
    name: 'Harini Sundar',
    rollNumber: '22IT052',
    department: 'IT',
    year: '3rd Year',
    email: 'harini.22it052@srms.edu',
    phone: '+91 94452 99001',
    gpa: 8.78,
    attendance: 95,
    status: 'Active',
    performanceSummary: 'Detail-oriented and dedicated team player. Leads the department technical paper presentation events.',
    courses: ['Software Engineering', 'Microprocessors & Microcontrollers', 'Compiler Design', 'Java Lab']
  },
  {
    id: 9,
    name: 'Ishaan Verma',
    rollNumber: '24IT005',
    department: 'IT',
    year: '1st Year',
    email: 'ishaan.24it005@srms.edu',
    phone: '+91 81442 88776',
    gpa: 8.40,
    attendance: 91,
    status: 'Active',
    performanceSummary: 'Enthusiastic freshman with intermediate programming experience. Participated in the first-year coding sprint.',
    courses: ['Programming in C', 'Engineering Graphics', 'Calculus & Matrices', 'Chemistry Laboratory']
  },
  {
    id: 10,
    name: 'Janani Krishnan',
    rollNumber: '23IT012',
    department: 'IT',
    year: '2nd Year',
    email: 'janani.23it012@srms.edu',
    phone: '+91 98845 22334',
    gpa: 9.62,
    attendance: 99,
    status: 'Active',
    performanceSummary: 'Department topper for consecutive semesters. Shows remarkable aptitude in algorithms and logical design.',
    courses: ['Data Structures & Algorithms', 'Digital Principles', 'Object Oriented Programming', 'Transforms & PDE']
  },
  {
    id: 11,
    name: 'Karthik Raja',
    rollNumber: '23AD056',
    department: 'AIDS',
    year: '2nd Year',
    email: 'karthik.23ad056@srms.edu',
    phone: '+91 97890 55667',
    gpa: 7.20,
    attendance: 84,
    status: 'Active',
    performanceSummary: 'Creative thinker, often designs unique solutions for projects. Member of the college robotics team.',
    courses: ['Design Thinking', 'Python Programming', 'Probability and Queueing', 'Physics Laboratory']
  },
  {
    id: 12,
    name: 'Leela Prasad',
    rollNumber: '21IT098',
    department: 'IT',
    year: '4th Year',
    email: 'leela.21it098@srms.edu',
    phone: '+91 86088 11224',
    gpa: 8.35,
    attendance: 89,
    status: 'Active',
    performanceSummary: 'Completed a summer internship at Amazon. Already placed at a reputable software firm during campus recruitments.',
    courses: ['Internet of Things', 'Mobile Computing', 'Cyber Forensics', 'Main Project Work']
  },
  {
    id: 13,
    name: 'Manoj Kumar',
    rollNumber: '22AD033',
    department: 'AIDS',
    year: '3rd Year',
    email: 'manoj.22ad033@srms.edu',
    phone: '+91 90031 99887',
    gpa: 6.80,
    attendance: 75,
    status: 'On Leave',
    performanceSummary: 'On medical leave for the past two weeks. Needs special makeup classes and lab sessions upon return.',
    courses: ['Artificial Intelligence', 'Optimization Techniques', 'Database Management', 'Data Exploration Lab']
  },
  {
    id: 14,
    name: 'Nisha Hegde',
    rollNumber: '24AD042',
    department: 'AIDS',
    year: '1st Year',
    email: 'nisha.24ad042@srms.edu',
    phone: '+91 72001 33440',
    gpa: 8.70,
    attendance: 93,
    status: 'Active',
    performanceSummary: 'Strong performance in introductory computer science and mathematics. Active member of the music club.',
    courses: ['Problem Solving with Python', 'Calculus', 'Basic Electrical Engineering', 'Design Thinking']
  },
  {
    id: 15,
    name: 'Pranav Shah',
    rollNumber: '21AD055',
    department: 'AIDS',
    year: '4th Year',
    email: 'pranav.21ad055@srms.edu',
    phone: '+91 98410 99882',
    gpa: 9.80,
    attendance: 100,
    status: 'Active',
    performanceSummary: 'Academic excellence with a perfect attendance record. Published a research paper on computer vision in IEEE.',
    courses: ['Computer Vision', 'Deep Learning', 'Reinforcement Learning', 'Research Seminar']
  },
  {
    id: 16,
    name: 'Rithika Sen',
    rollNumber: '22IT044',
    department: 'IT',
    year: '3rd Year',
    email: 'rithika.22it044@srms.edu',
    phone: '+91 95661 55662',
    gpa: 8.15,
    attendance: 87,
    status: 'Active',
    performanceSummary: 'Excellent organizational and presentation skills. Serves as student representative in the department committee.',
    courses: ['Computer Networks', 'Theory of Computation', 'Software Engineering', 'Graphics Laboratory']
  },
  {
    id: 17,
    name: 'Sanjay Dutt',
    rollNumber: '23IT089',
    department: 'IT',
    year: '2nd Year',
    email: 'sanjay.23it089@srms.edu',
    phone: '+91 88701 44550',
    gpa: 7.50,
    attendance: 81,
    status: 'Active',
    performanceSummary: 'Enthusiastic web developer. Developed an event registration app for the college cultural festival.',
    courses: ['Object Oriented Programming', 'Digital Systems', 'Discrete Mathematics', 'Web Tech Lab']
  },
  {
    id: 20,
    name: 'Yashaswini Sen',
    rollNumber: '21IT023',
    department: 'IT',
    year: '4th Year',
    email: 'yash.21it023@srms.edu',
    phone: '+91 98400 77889',
    gpa: 8.65,
    attendance: 94,
    status: 'Active',
    performanceSummary: 'Strong skills in cloud platforms (AWS/GCP). Selected as the Google Developer Student Club Lead for this year.',
    courses: ['Cloud Computing', 'Web Security', 'Big Data Engineering', 'Capstone Project']
  }
];
